### ISSUE TITLE
Select multiple nodes

### ISSUE THREAD

**Issue by denkomanceski** [cheton/infinite-tree#11]
Hi, I thought of another useful feature. Can we select multiple nodes? so for example, when I press ctrl I will be able to select more than one, and shift from index to index, etc..

Thanks

**Comment by denkomanceski** [comment]
I tried collecting the nodes in array (when the ctrlKey is true on the click event), and than
```this.multiSelectedNodes.forEach(n => this.tree.updateNode(n, {selected: true}))``` but doesnt work

**Comment by denkomanceski** [comment]
n.state.selected seems to work. Is it okay to use it like that directly?

**Comment by cheton** [comment]
Implementing multi-selection requires lots of code changes, I may not have time to do it shortly.

For now, I think it's fine to use `node.state.selected`, you can share your sample code if you found a good solution to it. :)

**Comment by denkomanceski** [comment]
I am just doing 
```
node.state.selected = true
tree.updateNode(node, {})
```
and adding this node in an array (if its already added, than the user expects to unselect that one, so I am unselecting and removing from the array)
When it is a single click, I unselect everything in the array and reset the array to []

P.S. The first time i push something in the array, I am adding the currently selected node (getSelectedNode()), because people usually select the first one normally, than press ctrl for the next ones. Of course if he pressed ctrl from the start, I am not adding the currently selected because its already there

I do not need shift for now, but ctrl works like a charm :D

**Comment by cheton** [comment]
Added a `getNodeFromPoint(x, y)` API in 1.10.0. I also added a complete multiple selection example that can be triggered by ctrl or meta key. You can check it below:

https://github.com/cheton/infinite-tree/blob/master/examples/default/index.js#L86
```js
let selectedNodes = [];
tree.on('click', (event) => {
    console.log('click', event);

    const currentNode = tree.getNodeFromPoint(event.x, event.y);
    if (!currentNode) {
        return;
    }

    const multipleSelectionMode = event.ctrlKey || event.metaKey;

    if (!multipleSelectionMode) {
        if (selectedNodes.length > 0) {
            // Call event.stopPropagation() to stop event bubbling
            event.stopPropagation();

            // Empty an array of selected nodes
            selectedNodes.forEach(selectedNode => {
                selectedNode.state.selected = false;
                tree.updateNode(selectedNode, {}, { shallowRendering: true });
            });
            selectedNodes = [];

            // Select current node
            tree.state.selectedNode = currentNode;
            currentNode.state.selected = true;
            tree.updateNode(currentNode, {}, { shallowRendering: true });
        }
        return;
    }

    // Call event.stopPropagation() to stop event bubbling
    event.stopPropagation();

    const selectedNode = tree.getSelectedNode();
    if (selectedNodes.length === 0 && selectedNode) {
        selectedNodes.push(selectedNode);
        tree.state.selectedNode = null;
    }

    const index = selectedNodes.indexOf(currentNode);

    // Remove current node if the array length of selected nodes is greater than 1
    if (index >= 0 && selectedNodes.length > 1) {
        currentNode.state.selected = false;
        selectedNodes.splice(index, 1);
        tree.updateNode(currentNode, {}, { shallowRendering: true });
    }

    // Add current node to the selected nodes
    if (index < 0) {
        currentNode.state.selected = true;
        selectedNodes.push(currentNode);
        tree.updateNode(currentNode, {}, { shallowRendering: true });
    }
});
```
