### ISSUE TITLE
Licensing issue on clusterize.js

### ISSUE THREAD

**Issue by wboyle-erwin** [cheton/infinite-tree#13]
I noticed the license for clusterize.js has changed from MIT to GPLv3. 

While this would not cause any issues for people with personal projects, this would cause problems with folks using your tree library for commercial usage.

https://github.com/NeXTs/Clusterize.js/blob/master/LICENSE

Not sure if you are aware of this.

**Comment by cheton** [comment]
Thank you for reporting this issue. Actually, I'm not aware of the license change. I will soon rewrite the code or look for an alternative solution.

**Comment by cheton** [comment]
Removed the dependency of clusterize.js since [v1.13.0](https://github.com/cheton/infinite-tree/releases/tag/v1.13.0)
