### ISSUE TITLE
filtering can sometimes cause an uncaught type error

### ISSUE THREAD

**Issue by firetiger77** [cheton/infinite-tree#16]
Even when using the function below to explicitly turn the search field into a string, I sometimes encounter an error "uncaught typeerror. filterText.toLowercase() is not a function", at infinite-tree.js, line 770.

If I add a ".toString() call on that line so it looks like this:
                    filterText = filterText.toString().toLowerCase();

I no longer encounter the error.

    onUpdateSearchField(e)
    {        
        if(this.tree)
        {            
            //console.log("filtering tree2 with");
            this.tree.filterString = e.target.value.toString();            
            this.tree.filter(this.tree.filterString, filterOptions);            
        }
    }

**Comment by cheton** [comment]
https://github.com/cheton/infinite-tree/blob/master/src/infinite-tree.js#L694
```js
let filterText = get(node, options.filterPath, '');
```

The code above assumes that your Node object always has a property like "name", which is specified by the "filterPath" option. However, the key might not be available in your Node object or not a string, I should do the conversion for the return result of filterText. Thank you for reporting this bug.

**Comment by cheton** [comment]
Fixed in [v1.14.1](https://github.com/cheton/infinite-tree/releases/tag/v1.14.1)
