### ISSUE TITLE
Minimum working example

### ISSUE THREAD

**Issue by fralik** [cheton/infinite-tree#28]
Hi!
It will be great to have a minimum working example to start with. Right now, I've tried example from README, but it outputs just ![a list.](https://user-images.githubusercontent.com/191278/37584217-ee281ee8-2b54-11e8-89b9-f091de35e39a.png)

Page with examples is also of little help since it contains several examples and all the code is organized to accommodate these examples.

[HTML page](https://github.com/cheton/infinite-tree/files/1824168/infiniteTree.zip) that I used.

Thanks!

**Comment by cheton** [comment]
A tree can be rendered in any form, it depends on how you implement your rowRenderer. 

Check out this for a bare minimum example of rowRenderer:
https://github.com/cheton/infinite-tree/blob/master/examples/default/renderer.js

**Comment by husanhong3** [comment]
![image](https://user-images.githubusercontent.com/38035410/38242564-b1567680-3767-11e8-9dff-7d7be43faddd.png)
Why some nodes do not display?
Thank you!

**Comment by fralik** [comment]
@cheton Thanks! I struggle to run it though. What kind of Javascript is it? I have syntax errors on 'import' keyword.
