### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fralik** [cheton/infinite-tree#29]
As I understood, infinite-tree is based on clusterize.js. Clusterize is available either under commercial license or under GNU GPL v3. If I understand correctly it is not possible to release derived work (infinite-tree) under MIT if you use GPL's version of clusterize.

**Comment by cheton** [comment]
The dependency has been removed since [v1.13.0](https://github.com/cheton/infinite-tree/releases/tag/v1.13.0). You can use v1.13.0 or a higher version to avoid GPL violation.
