### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by bharatpatil** [cheton/infinite-tree#3]
Any recommendations on filterings?

**Comment by cheton** [comment]
By now there is no filtering API in infinite-tree, but you can try this way before the API is implemented:

1. Iterate over each node, if a filter criteria is matched, mark a flag (e.g. filtered = true ) to the node and all of its parent nodes.
2. In your `rowRenderer`, if the flag is not set, set `display: none` to hide this node.
3. Call the `update` method to update the tree.

The sample code below is using ES6/7 syntax:
```js
let isFilterMode = false;

const tree = new InfiniteTree(el, {
    rowRenderer: (node) => {
        const { id, props = {} } = node;
        const { filtered = true } = props; // defaults to true

        if (isFilterMode && !filtered) {
            return `<div data-id="${id}" style="display: none" />`;
        }

        return `<div data-id="${id}" class="infinite-tree-item" />`;
    }
});

// Turn on filter mode
tree.isFilterMode = true;

// Filter nodes
const searchKeyword = 'keyword';
tree.nodes.forEach((node) => {
    node.props = node.props || {};

    if (node.name.indexOf(searchKeyword) < 0) {
        node.props.filtered = false;
        return;
    }

    while (node && node.parent) {
        node.props.filtered = true;
        node = node.parent;
    }
});

// Update tree
tree.update();

// You can turn off filter mode at any time
tree.isFilterMode = false;
tree.update();

```

**Comment by mudcube** [comment]
This works well for me. There is one issue that can potentially come up using this method however:  if the first row (root) is hidden it throws off Clusterize calculation of scroll height initially. A workaround is to run `tree.scrollTop(1)` on the initial run. This is not ideal, but works in the meantime until a better solution is available.

**Comment by cheton** [comment]
Added in v1.12.0
