### ISSUE TITLE
Adding Indentation lines

### ISSUE THREAD

**Issue by 94mc** [cheton/infinite-tree#33]
Hi,

I am looking to add indentation lines to different levels of the tree when the parent node is expanded.

Is this something that can be achieved / would you be able to point me in the right direction as to do so?

I have attached an image which will show more clearly what im looking to do.

![indentation lines](https://user-images.githubusercontent.com/40669752/42046110-09562bc0-7af5-11e8-872d-0925503d2cab.png)

Any help is greatly appreciated, thank you

**Comment by cheton** [comment]
See example here: https://github.com/cheton/flattree#nested-hierarchy

```js
flatten(tree, { openAllNodes: true }).forEach((node, index) => {
    const { state, label = '', children = [] } = node;
    const { depth, open, path, prefixMask } = state;

    if (depth === 0) {
        console.log('%s (%s)', label, path);
        return;
    }

    const prefix = prefixMask.substr(1).split('')
        .map(s => (Number(s) === 0) ? '  ' : '| ')
        .join('');

    console.log('%s%s─%s %s (%s)', prefix, (node.isLastChild() ? '└' : '├'), (node.hasChildren() && open ? '┬' : '─'), label, path);
});
```

You can render indentation lines by referring to the prefixMask value of a node's state.
