### ISSUE TITLE
Demo site not loading with IE11

### ISSUE THREAD

**Issue by mikeprimm** [cheton/infinite-tree#35]
Browsing to the demo site - https://infinite-tree.js.org/examples.html#/default - with IE11 yields a frozen progress indicator spinner, but nothing else.  Looking at the developer tools, I see nothing in the Console and no Network errors - just a lack of any signs of progress on initializing.  I can select across the different demo links, with the corresponding URL update being reflected in the browser, but no change in the appearance.

![image](https://user-images.githubusercontent.com/654487/42462286-6f773c7a-8368-11e8-8ba3-4c7ee5dc4bb9.png)

We're seeing similar issues with attempting to use the component in our code, but the fact that it isn't working on the demo site seemed like the best reproduce scenario we could find :)

**Comment by cheton** [comment]
Have you tried clearing browser cache? I didn't encounter the issue with IE 11.

![image](https://user-images.githubusercontent.com/447801/42524967-9df30984-84a4-11e8-8800-7a956bf19373.png)

**Comment by mikeprimm** [comment]
I started trying to do some debug on this - best I can tell, the getNodeFromPoint (https://github.com/cheton/infinite-tree/blob/eddda39684c600d920f66fabf3124c6b5d1c0322/src/infinite-tree.js#L943) on the click event isn't matching the right element.  Still trying to get a feel for the code, but that seemed to be where the click handling behavior diverged between Chrome vs IE 11

**Comment by mikeprimm** [comment]
When the node is clicked - even the second time where we see the checkbox, the propagated behavior for the other nodes isn't happening (see below):
![image](https://user-images.githubusercontent.com/654487/42583283-46ecc93e-84f6-11e8-9d6b-459c65c63b6e.png)

**Comment by mikeprimm** [comment]
OK - I think I've got this worked out: the problem is the fact that we're using the 'event.x' and 'event.y' attributes for the click position, versus 'event.clientX' and 'event.clientY'.  On other browsers, these are the same - pixel position of the click.  On IE11, event.x and event.y are floating point offsets that are not the same as clientX,clientY.  A hand fixed set of code worked properly, so I'm feeling optimistic that this will be a good fix.

**Comment by mikeprimm** [comment]
Submitted PR with changes to documents and sample code.
