### ISSUE TITLE
Flickering when scrolling down

### ISSUE THREAD

**Issue by nevermind10844** [cheton/infinite-tree#56]
Hey there,

I have a tree view displaysing a couple of hundred items.
When scrolling down to a certain position it begins to flicker like crazy.
Going up and down from empty space to some elements above.

When I manipulate the rowsInBlock or blockInCluster to where no scrolling would be needed, it just works fine. But that is not what I would like to do to fix it.

Can you help me out?

Thanks in advance!

**Comment by sandupostaru** [comment]
Hello,

Any news regarding this issue? Have you managed to find a solution?

Thanks!

**Comment by nevermind10844** [comment]
> Hello,
> 
> Any news regarding this issue? Have you managed to find a solution?
> 
> Thanks!

Nothing unfortunately,

**Comment by sandupostaru** [comment]
That's too bad...
Have you explored other react tree libraries by any chance?

**Comment by cheton** [comment]
Hi @nevermind10844 

You can try to create an example on CodeSandbox that will always reproduce the flickering issue. This can help accerlerate the issue resolution time.

**Comment by cheton** [comment]
v1.17.0 might help if you can find a good option to control the number of rows and blocks to be rendered

See PR https://github.com/cheton/infinite-tree/pull/54
