### ISSUE TITLE
Angular2 support

### ISSUE THREAD

**Issue by denkomanceski** [cheton/infinite-tree#7]
I am planning to wrap the tree in an angular component and expose some APIs, so it will be usable in angular, but since I dont have a lot of knowledge about how the renderer works on this tree yet, could you maybe in short elaborate what would be the best way to do it and if it is doable at all?

Another thing that I was concerned about was the following scenario:
- Lets assume that I have 5 nodes, and when I expand the 2nd node, it is so long that even the hidden nodes which are in the DOM are part of it, and the 3rd (its sibling) node is not on the dom yet. What would happen if I collapse the 2nd node? Will the 3rd node become visible instantly? Here is a screenshot of what I mean: http://prntscr.com/e5q5cg
- Is it possible to add Branch lines and how complicated it will be? (Since the tree is linear in the DOM, and not nested). Here is what I mean by Branch Lines: http://prntscr.com/e5q5td

Regards

**Comment by cheton** [comment]
Sorry for that I don't have experiences about Angular. Within [react-infinite-tree](https://github.com/cheton/react-infinite-tree), I use React's server-side rendering to render a component into HTML, so you don't need to output HTML string in the renderer.
https://github.com/cheton/react-infinite-tree/blob/master/src/index.jsx#L39
```js
        const rowRenderer = options.rowRenderer || defaultRowRenderer;
        options.rowRenderer = (node, opts) => {
            let row = rowRenderer(node, opts);
            if (typeof row === 'object') {
                // Use ReactDOMServer.renderToString() to render React Component
                row = ReactDOMServer.renderToString(row);
            }
            return row;
        };
```

Answer your questions:
1. Yes, it will become visible instantly.
2. You can take a look at https://github.com/cheton/flattree#nested-hierarchy to learn how to add branch lines. [sample code](https://github.com/cheton/flattree/blob/master/examples/tree2.js)

**Comment by denkomanceski** [comment]
Great, thank you.. I will let you know when there is some usable version of Angular.
