### ISSUE TITLE
Resizing the tree

### ISSUE THREAD

**Issue by denkomanceski** [cheton/infinite-tree#8]
Hi, I tried to flex the tree's container to fit the screen, but the tree gets hidden after some scrolling.. What would be the best way to change the height of the tree dynamically based on the screen size? Manually increase the height or ?
Ty
Regards

**Comment by cheton** [comment]
Take a look at the example:
https://infinite-tree.js.org/examples.html#/classic

You can update the max-height accordingly.

![image](https://cloud.githubusercontent.com/assets/447801/23254818/4cbe3264-f9f4-11e6-9bff-c0fd279c8f96.png)


If you want to fit the view port height, use `max-height: calc(100vh - 100px)`, where 100px is the padding when necessary.
